package app.theygrow;

import android.os.SystemClock;

import androidx.activity.OnBackPressedCallback;

import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * The hardware back button, handed to the page that knows where the parent is
 * (NAV-P3).
 *
 * <p>WHY THIS EXISTS AT ALL. Until this packet Back had no meaning inside the
 * app: {@code @capacitor/android} 8.5.0 installs no back handling of its own, so
 * every press went to the platform and the app went to the background — out of an
 * open window, out of the middle of a form, from anywhere. That is why windows
 * carried their own back arrows: not because a window wants an arrow, but because
 * the button did not work.
 *
 * <p>WHY A FIRST-PARTY PLUGIN RATHER THAN {@code @capacitor/app}. Cost, both
 * ways, because the trade is not obvious. That plugin would give a tested
 * {@code backButton} listener and {@code minimizeApp()} for no Java at all — but
 * it is a shipped npm dependency and the supply-chain review {@code
 * app/tests/store-supply-chain.spec.js} exists to make one expensive, and, which
 * settles it, its event is delivered through the {@code Plugins} proxy in {@code
 * @capacitor/core}: THIS PRODUCT LOADS NO NPM JAVASCRIPT AT ALL, has no bundler
 * and no import map, so {@code Plugin.notifyListeners} would resolve against an
 * {@code addListener} call that nothing here ever makes. The event would be sent
 * and nobody would hear it. This class sends a plain window event through {@code
 * Bridge.triggerWindowJSEvent}, which the INJECTED {@code native-bridge.js}
 * implements ({@code Capacitor.triggerEvent} → {@code window.dispatchEvent}) with
 * no npm code in the picture, and follows the standing precedent of {@link
 * ExportSinkPlugin} and {@link BuildInfoPlugin}: registered by hand in {@link
 * MainActivity}, because {@code capacitor.plugins.json} is generated by {@code
 * cap sync}, is gitignored, and lists only plugins that arrive through npm.
 *
 * <p>IT SHIPS DISARMED, AND THAT IS THE FAIL-CLOSED HALF. The callback is
 * registered with {@code false} and is enabled only when the page calls {@link
 * #arm}. An app whose JavaScript never ran, or ran and never armed, behaves
 * exactly as it did before this packet — the platform default. Nothing about the
 * back button can be broken by this class before the page is there to answer for
 * it.
 *
 * <p>AND IT FAILS OPEN UNDER A WEDGE, WHICH IS THE OTHER HALF. Every press is
 * handed to the page and waits for exactly one answer — {@link #handled} or
 * {@link #passThrough}. If the WebView is wedged, no answer ever comes; so a
 * press arriving while an earlier one has stood unanswered for longer than the
 * deadline takes the platform default itself. A family whose Back button has
 * stopped working is a worse failure than any navigation defect this packet
 * fixes.
 *
 * <p>THE DEADLINE IS NOT A LITERAL HERE. It arrives as an argument to {@link
 * #arm} from {@code NAV_CONFIG.backAnswerDeadlineMs}, on the rule the update
 * check already follows for its own timeout: one declaration, in the declared
 * place, and no second copy that can drift. A call without a usable deadline is
 * REJECTED rather than defaulted — arming on a guessed number would be arming on
 * a number nobody declared.
 *
 * <p>«LET THE SYSTEM DEFAULT HAPPEN» IS IMPLEMENTED AS EXACTLY THAT. {@link
 * #platformDefault} disables this callback and re-dispatches the press, so the
 * platform decides what a root {@code singleTask} activity does with Back. It is
 * deliberately NOT {@code moveTaskToBack(true)}: that would be a second copy of a
 * platform rule which has already changed once, and it would be ours to keep
 * right.
 *
 * <p>WHAT IT CANNOT DO. It reads nothing, stores nothing between presses but a
 * timestamp, opens no file, touches no network, and carries no data of any kind
 * into or out of the page — the event it sends has no payload at all. Nothing
 * here is family data or is derived from any.
 */
@CapacitorPlugin(name = "TheyGrowBack")
public class BackButtonPlugin extends Plugin {

    /**
     * The window event the page listens for. Mirrored in {@code
     * app/m/v10/surfaces/back.js} as {@code BACK_EVENT}; the two are one
     * protocol constant with two ends, and {@code app/tests/back-button.spec.js}
     * reads the page side rather than retyping it.
     */
    private static final String BACK_EVENT = "theygrowback";

    private OnBackPressedCallback intercept;

    /** How long an unanswered press may stand. Set by {@link #arm}, never guessed. */
    private volatile long answerDeadlineMs;

    /** When the press now awaiting an answer was received, or 0 for none. */
    private volatile long pressAwaitingAnswerAt;

    @Override
    public void load() {
        intercept = new OnBackPressedCallback(false) {
            @Override
            public void handleOnBackPressed() {
                onBackPressed();
            }
        };
        getActivity().getOnBackPressedDispatcher().addCallback(getActivity(), intercept);
    }

    /** Runs on the UI thread, from the dispatcher. */
    private void onBackPressed() {
        long now = SystemClock.uptimeMillis();
        long pending = pressAwaitingAnswerAt;
        if (pending != 0L && now - pending > answerDeadlineMs) {
            // The page has not answered the previous press within the declared
            // deadline. Stop waiting for it; a Back that does nothing is worse
            // than a Back that leaves.
            pressAwaitingAnswerAt = 0L;
            platformDefault();
            return;
        }
        pressAwaitingAnswerAt = now;
        getBridge().triggerWindowJSEvent(BACK_EVENT);
    }

    /** Hands the press back to the platform, with this interceptor stood down. */
    private void platformDefault() {
        intercept.setEnabled(false);
        getActivity().getOnBackPressedDispatcher().onBackPressed();
        intercept.setEnabled(true);
    }

    /**
     * Starts intercepting, with the deadline the page declares.
     *
     * <p>Idempotent: the page calls it once at wiring, and calling it again only
     * restates the same two facts.
     */
    @PluginMethod
    public void arm(PluginCall call) {
        Integer deadline = call.getInt("deadlineMs");
        if (deadline == null || deadline <= 0) {
            call.reject("the back button needs a declared answer deadline to arm");
            return;
        }
        answerDeadlineMs = deadline;
        getActivity().runOnUiThread(() -> intercept.setEnabled(true));
        call.resolve();
    }

    /** The page dealt with the press itself. */
    @PluginMethod
    public void handled(PluginCall call) {
        pressAwaitingAnswerAt = 0L;
        call.resolve();
    }

    /** The page had nothing to deal with; the platform decides. */
    @PluginMethod
    public void passThrough(PluginCall call) {
        pressAwaitingAnswerAt = 0L;
        getActivity().runOnUiThread(this::platformDefault);
        call.resolve();
    }
}
