package app.theygrow;

import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.Build;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * Which build is installed, and where it came from (NAV-P2).
 *
 * <p>WHY THIS EXISTS AT ALL. The update check compares two numbers: the
 * {@code versionCode} of the release published on the distribution page, and the
 * {@code versionCode} of the build the parent is holding. The second one was not
 * reachable from JavaScript in this product — nothing has ever exposed it. The
 * former {@code APP_VERSION} constant in the shell existed only to enrich GA4
 * events and left with analytics at UIP-P1.
 *
 * <p>WHY A FIRST-PARTY PLUGIN RATHER THAN {@code @capacitor/app}. That plugin
 * would answer the version and nothing else, at the cost of a shipped npm
 * dependency and the supply-chain review {@code
 * app/tests/store-supply-chain.spec.js} exists to make expensive. This class
 * answers both questions the packet has — the version and the installer — in
 * three {@code PackageManager} reads, adds no dependency, and follows the
 * standing precedent of {@link ExportSinkPlugin}: a first-party plugin
 * registered by hand in {@link MainActivity}, because {@code
 * capacitor.plugins.json} is generated by {@code cap sync}, is gitignored, and
 * lists only plugins that arrive through npm.
 *
 * <p>WHY NOT A BUILD-TIME CONSTANT IN THE WEB ROOT. The two delivery channels
 * ship byte-identical assets ({@code LSC-P1-INV-002}), {@code
 * native/tools/stage-webdir.js} is a byte copy that rewrites nothing, and the
 * version is not known until Gradle has run. Stamping it into the staged root
 * would break the identity the parity suite asserts in both directions, to carry
 * one integer.
 *
 * <p>WHAT IT CANNOT DO, which is the point of it being this small. It reads
 * three fields of this application's own package entry. It needs no permission —
 * not {@code QUERY_ALL_PACKAGES}, not anything — because a package may always
 * read its own record; it enumerates nothing, queries no other package, opens no
 * file, touches no network and holds no state between calls. Nothing it returns
 * is family data or is derived from any: a version number, a version name and
 * the name of the store that installed the app.
 */
@CapacitorPlugin(name = "TheyGrowBuild")
public class BuildInfoPlugin extends Plugin {

    /**
     * Reports the installed build and its installer.
     *
     * <p>{@code installer} is deliberately allowed to be {@code null} and the JS
     * side treats {@code null} as "not Play". A sideloaded install — which is
     * what the whole GitHub channel is — reports {@code null}, or the package
     * name of the browser or file manager the {@code .apk} was opened from.
     * There is no positive token that means "this came from our release page",
     * which is why {@code surfaces/channel.js} gates on the Play token rather
     * than on the absence of one, and says so at the knob.
     *
     * <p>Two APIs for one question, because the platform split them at 30 and
     * {@code minSdk} here is 24. {@code getInstallSourceInfo} is the current one;
     * {@code getInstallerPackageName} is deprecated and is the only one the older
     * half of the supported range has. Both are wrapped: the documented
     * {@code NameNotFoundException} cannot happen for our own package, and if the
     * platform ever disagreed the honest answer is "unknown installer", which
     * lands on the same branch as a sideload.
     */
    @PluginMethod
    public void info(PluginCall call) {
        JSObject result = new JSObject();
        String pkg = getContext().getPackageName();
        PackageManager packages = getContext().getPackageManager();

        try {
            PackageInfo info = packages.getPackageInfo(pkg, 0);
            result.put("versionName", info.versionName);
            // getLongVersionCode() from 28; the low 32 bits are versionCode, and
            // this project never sets versionCodeMajor, so the cast is exact.
            long code = Build.VERSION.SDK_INT >= Build.VERSION_CODES.P
                    ? info.getLongVersionCode()
                    : (long) info.versionCode;
            result.put("versionCode", (int) code);
        } catch (PackageManager.NameNotFoundException error) {
            // Unreachable for our own package; refused rather than guessed,
            // because a missing version must not read as "up to date".
            call.reject("the installed build could not be read");
            return;
        }

        result.put("installer", installerOf(pkg, packages));
        call.resolve(result);
    }

    /** The package that installed this one, or {@code null} if that is unknown. */
    private static String installerOf(String pkg, PackageManager packages) {
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                return packages.getInstallSourceInfo(pkg).getInstallingPackageName();
            }
            return packages.getInstallerPackageName(pkg);
        } catch (Exception error) {
            return null;
        }
    }
}
