package app.theygrow;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.util.Base64;

import androidx.activity.result.ActivityResult;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.ActivityCallback;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.IOException;
import java.io.OutputStream;

/**
 * The export sink (L1-P3): writes the archive to a document the parent picked.
 *
 * <p>WHY THIS EXISTS INSTEAD OF A FILESYSTEM PLUGIN. The archive is unencrypted
 * family data, so where it lands is a privacy decision. {@code
 * ACTION_CREATE_DOCUMENT} needs <b>no storage permission at all</b> — the system
 * picker returns a URI for the single document the parent chose in that moment,
 * and this plugin can write that document and nothing else. It cannot list a
 * directory, cannot read a file, cannot delete anything, and cannot write to a
 * path of its own choosing. A general filesystem plugin would grant a far wider
 * capability than the contour needs, and would add an npm dependency to a
 * shipped surface that deliberately has none.
 *
 * <p>THE APP-SIDE ALLOWLIST IS THE OTHER HALF. {@code
 * app/m/v1/export/config.js} declares exactly one callable method and {@code
 * app/tests/store-supply-chain.spec.js} fails if a call site reaches past it.
 * One method here, one method there.
 *
 * <p>Registered explicitly in {@link MainActivity}: {@code capacitor.plugins.json}
 * is generated by {@code cap sync} and gitignored, so it never lists a
 * first-party plugin and must not be hand-edited.
 */
@CapacitorPlugin(name = "TheyGrowExport")
public class ExportSinkPlugin extends Plugin {

    /**
     * Opens the system file picker, then writes the archive to what it returns.
     *
     * <p>The bytes arrive base64-encoded because the Capacitor bridge carries
     * JSON. They are decoded here and streamed straight out; nothing is written
     * to a temporary file on the way, so there is no moment where an unencrypted
     * copy of the family's history sits somewhere nobody chose.
     */
    @PluginMethod
    public void createDocument(PluginCall call) {
        String filename = call.getString("filename");
        String mimeType = call.getString("mimeType", "application/octet-stream");
        if (filename == null || call.getString("base64") == null) {
            call.reject("createDocument needs a filename and base64 payload");
            return;
        }

        Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType(mimeType);
        intent.putExtra(Intent.EXTRA_TITLE, filename);

        // The call is saved so its payload survives the trip through the picker:
        // the activity can be recreated while the system UI is in front, and a
        // payload held only in a field would be gone when the result arrives.
        bridge.saveCall(call);
        startActivityForResult(call, intent, "onDocumentCreated");
    }

    @ActivityCallback
    private void onDocumentCreated(PluginCall call, ActivityResult result) {
        if (call == null) {
            return;
        }

        // A closed picker is a decision, not a failure. It resolves with
        // saved=false so the app can stay silent rather than reporting an error
        // the parent did not cause.
        if (result.getResultCode() != Activity.RESULT_OK || result.getData() == null) {
            JSObject cancelled = new JSObject();
            cancelled.put("saved", false);
            cancelled.put("reason", "cancelled");
            call.resolve(cancelled);
            return;
        }

        Uri uri = result.getData().getData();
        if (uri == null) {
            call.reject("the file picker returned no document");
            return;
        }

        try {
            writeDocument(getContext(), uri, call.getString("base64"));
        } catch (IOException | IllegalArgumentException error) {
            // The engine's own message, never the archive's contents.
            call.reject("the archive could not be written: " + error.getMessage());
            return;
        }

        JSObject saved = new JSObject();
        saved.put("saved", true);
        saved.put("uri", uri.toString());
        call.resolve(saved);
    }

    /**
     * Decodes the payload and streams it into the chosen document.
     *
     * <p>Extracted from {@link #onDocumentCreated} so the byte path can be
     * exercised on a real device without driving the system file picker's UI —
     * see {@code ExportSinkTest}. The picker is the part an instrumented test
     * cannot honestly automate; the decode and the write are the part that can
     * silently corrupt an archive, so that is the part the test covers.
     *
     * <p>{@code "wt"} truncates: writing a shorter archive over a longer one must
     * not leave the tail of the old file behind, which would produce a zip whose
     * central directory says one thing and whose bytes say another.
     */
    static void writeDocument(android.content.Context context, Uri uri, String base64)
            throws IOException {
        byte[] bytes = Base64.decode(base64, Base64.DEFAULT);
        try (OutputStream out = context.getContentResolver().openOutputStream(uri, "wt")) {
            if (out == null) {
                throw new IOException("the chosen document could not be opened for writing");
            }
            out.write(bytes);
            out.flush();
        }
    }
}
