package app.theygrow;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.util.Base64;

import androidx.activity.result.ActivityResult;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.ActivityCallback;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;

/**
 * The export sink (L1-P3, transfer repaired in XPT-P1): writes the archive to a
 * document the parent picked.
 *
 * <p>WHY THIS EXISTS INSTEAD OF A FILESYSTEM PLUGIN. The archive is unencrypted
 * family data, so where it lands is a privacy decision. {@code
 * ACTION_CREATE_DOCUMENT} needs <b>no storage permission at all</b> — the system
 * picker returns a URI for the single document the parent chose in that moment,
 * and this plugin can write that document and nothing else. It cannot list a
 * directory, cannot read a file, cannot delete anything, and cannot write to a
 * path of its own choosing. A general filesystem plugin would grant a far wider
 * capability than the contour needs, and would add an npm dependency to a
 * shipped surface that deliberately has none. The three methods below do not
 * widen that by one byte: two of them hand bytes to a buffer inside this
 * process, and the third is the one that writes, to the same one place.
 *
 * <p>WHY THE ARCHIVE IS STAGED BEFORE THE PICKER OPENS (XPT-P1, measured, not
 * guessed). Until that packet the whole archive travelled as the {@code base64}
 * option of the call that starts the picker. That is the call Capacitor records
 * as {@code pluginCallForLastActivity}, and {@code Bridge.saveInstanceState}
 * writes its options JSON into the activity's saved instance state TWICE — once
 * directly, once inside this plugin's own bundle. On the family device on
 * 2026-08-15, with 1.73 MB of archive, the resulting 4 630 924-byte parcel
 * crossed the ~1 MB binder limit while the picker was in front and
 * {@code TransactionTooLargeException} killed the process: AFTER the system had
 * created the empty document with the chosen name, and BEFORE a byte was
 * written. A stable 0-byte file, with nothing in the app to read.
 *
 * <p>So the bytes arrive first, in bounded chunks, and the launching call
 * carries four small values. {@link #createDocument} REFUSES anything else —
 * an option key it does not declare, or options above
 * {@link #LAUNCH_OPTIONS_MAX_BYTES} — so the defect cannot come back through an
 * edit on the app side that looks harmless there. It also refuses to open the
 * picker at all unless the bytes it holds are exactly as many as the app says it
 * sent: the parent is never shown a save dialog for an archive that is not fully
 * in hand.
 *
 * <p>NOTHING IS WRITTEN TO A TEMPORARY FILE, then or now. The staged bytes live
 * in this process's memory until they go to the chosen document, so there is
 * still no moment where an unencrypted copy of the family's history sits
 * somewhere nobody chose — and they are dropped on success, on cancel and on
 * destroy rather than left behind.
 *
 * <p>THE APP-SIDE ALLOWLIST IS THE OTHER HALF. {@code
 * app/m/v3/export/config.js} declares exactly these three callable methods and
 * {@code app/tests/export-contour.spec.js} fails if a call site reaches past
 * them, or if the list grows without that test being changed on purpose. The
 * mount version in that path is kept current by {@code EMV-P5-INV-001} — it
 * still named the previous generation one bump after the shell had moved on,
 * which is the drift that invariant exists to end.
 *
 * <p>Registered explicitly in {@link MainActivity}: {@code capacitor.plugins.json}
 * is generated by {@code cap sync} and gitignored, so it never lists a
 * first-party plugin and must not be hand-edited.
 */
@CapacitorPlugin(name = "TheyGrowExport")
public class ExportSinkPlugin extends Plugin {

    /**
     * The only option keys {@link #createDocument} accepts. Mirrors the object
     * built in {@code app/m/v3/export/sink.js}; anything else is refused rather
     * than ignored, because "ignored" is how a payload gets back onto this call.
     */
    private static final List<String> LAUNCH_OPTION_KEYS =
            Arrays.asList("transferId", "filename", "mimeType", "totalBytes");

    /**
     * The ceiling on the serialized options of the call that starts the picker.
     *
     * <p>Mirrors {@code EXPORT_CONFIG.sinkLaunchOptionsMaxBytes} in {@code
     * app/m/v3/export/config.js}; the two languages share no config surface, so
     * the number is written in both places by hand and {@code
     * app/tests/export-contour.spec.js} asserts they agree — the same
     * arrangement {@code STORE_CONFIG.sqliteVersionFloor} has with {@code
     * app/tests/schema/harness.py}.
     */
    static final int LAUNCH_OPTIONS_MAX_BYTES = 4096;

    /**
     * The largest archive this plugin will stage, as a bound on its own heap.
     *
     * <p>Java-only on purpose, and NOT a knob in the app's config surface: it is
     * a property of the process holding the bytes, and the app could not act on
     * it if it knew it. A real archive is a few megabytes — 64 MiB is far above
     * anything the contour produces and far below a heap the app cannot survive,
     * so its whole job is to stop a runaway caller rather than to shape a
     * normal export.
     */
    private static final int MAX_STAGED_BYTES = 64 * 1024 * 1024;

    /**
     * The archive, in flight. Guarded by {@code this}: Capacitor dispatches
     * plugin calls on a pool thread, so the chunk that arrives and the picker
     * result that consumes them can be on different threads.
     */
    private ByteArrayOutputStream staged;

    private String transferId;
    private int declaredTotalBytes;

    /**
     * Opens a transfer and says how big it will be.
     *
     * <p>The size is taken up front so the buffer is allocated ONCE at exactly
     * the right size. A buffer that grew by doubling would hold two copies of a
     * multi-megabyte archive at every growth step, which is precisely the kind
     * of peak this packet exists to remove.
     */
    @PluginMethod
    public synchronized void beginTransfer(PluginCall call) {
        Integer total = call.getInt("totalBytes");
        if (total == null || total <= 0 || total > MAX_STAGED_BYTES) {
            discardTransfer();
            call.reject("beginTransfer needs a totalBytes within what this device will stage");
            return;
        }

        // A second beginTransfer discards the first. An export is a human action
        // on one button; two in flight means the first was abandoned, and
        // keeping abandoned family bytes around is the opposite of what this
        // plugin is for.
        discardTransfer();
        staged = new ByteArrayOutputStream(total);
        declaredTotalBytes = total;
        transferId = UUID.randomUUID().toString();

        JSObject opened = new JSObject();
        opened.put("transferId", transferId);
        call.resolve(opened);
    }

    /** Appends one chunk of the archive to the open transfer. */
    @PluginMethod
    public synchronized void appendChunk(PluginCall call) {
        String id = call.getString("transferId");
        String base64 = call.getString("base64");
        if (staged == null || transferId == null || !transferId.equals(id)) {
            call.reject("appendChunk names no open transfer");
            return;
        }
        if (base64 == null) {
            call.reject("appendChunk needs a base64 chunk");
            return;
        }

        byte[] chunk;
        try {
            chunk = Base64.decode(base64, Base64.DEFAULT);
        } catch (IllegalArgumentException error) {
            discardTransfer();
            call.reject("a chunk of the archive was not decodable");
            return;
        }
        if (staged.size() + chunk.length > declaredTotalBytes) {
            // Longer than declared means the two sides disagree about what is
            // being written. That is exactly the state in which a document must
            // not be created, so the transfer ends here rather than at the
            // picker.
            discardTransfer();
            call.reject("the transfer sent more bytes than it declared");
            return;
        }
        staged.write(chunk, 0, chunk.length);

        JSObject received = new JSObject();
        received.put("received", staged.size());
        call.resolve(received);
    }

    /**
     * Opens the system file picker, then writes the staged archive to what it
     * returns.
     *
     * <p>Every refusal below happens BEFORE the intent is built. The system
     * creates the document the moment the parent presses Save, so a failure
     * after that point is visible to them as a broken file — which is the shape
     * the measured defect took.
     */
    @PluginMethod
    public synchronized void createDocument(PluginCall call) {
        JSObject data = call.getData();

        // THE GUARD THAT CARRIES THIS PACKET. The options of this call are what
        // Capacitor persists into saved instance state, twice, when the picker
        // comes to the front. Refusing an undeclared key refuses a payload,
        // whatever it is called; refusing an oversized options object refuses
        // one that arrives inside a key that IS declared.
        Iterator<String> keys = data.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            if (!LAUNCH_OPTION_KEYS.contains(key)) {
                discardTransfer();
                call.reject(
                        "createDocument refuses the option \""
                                + key
                                + "\": the call that opens the file picker carries a reference to"
                                + " the staged archive and nothing else");
                return;
            }
        }
        int optionsBytes = data.toString().length();
        if (optionsBytes > LAUNCH_OPTIONS_MAX_BYTES) {
            discardTransfer();
            call.reject(
                    "createDocument refuses "
                            + optionsBytes
                            + " bytes of options: the call that opens the file picker must stay"
                            + " under "
                            + LAUNCH_OPTIONS_MAX_BYTES
                            + " bytes, because it is persisted into saved instance state");
            return;
        }

        String filename = call.getString("filename");
        String mimeType = call.getString("mimeType", "application/octet-stream");
        if (filename == null) {
            call.reject("createDocument needs a filename and a staged archive");
            return;
        }

        String id = call.getString("transferId");
        Integer total = call.getInt("totalBytes");
        if (staged == null || transferId == null || !transferId.equals(id)) {
            call.reject("createDocument names no open transfer");
            return;
        }
        if (total == null || total != staged.size() || total != declaredTotalBytes) {
            // The archive in hand is not the archive the app says it sent. No
            // picker, therefore no document, therefore no half-written file with
            // the right name — the failure the parent sees is "nothing
            // happened", which is the true one.
            int held = staged.size();
            discardTransfer();
            call.reject(
                    "the staged archive is "
                            + held
                            + " bytes where the app declared "
                            + total
                            + " — no document was created");
            return;
        }

        Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType(mimeType);
        intent.putExtra(Intent.EXTRA_TITLE, filename);

        // The call is saved so it survives the trip through the picker: the
        // activity can be recreated while the system UI is in front, and a call
        // held only in a field would be gone when the result arrives. What it
        // carries through that trip is now four small values — see the guard
        // above for why that sentence is load-bearing.
        bridge.saveCall(call);
        startActivityForResult(call, intent, "onDocumentCreated");
    }

    @ActivityCallback
    private synchronized void onDocumentCreated(PluginCall call, ActivityResult result) {
        if (call == null) {
            return;
        }

        // A closed picker is a decision, not a failure. It resolves with
        // saved=false so the app can stay silent rather than reporting an error
        // the parent did not cause. The staged bytes go with it: a parent who
        // said no should not leave their history sitting in a buffer.
        if (result.getResultCode() != Activity.RESULT_OK || result.getData() == null) {
            discardTransfer();
            JSObject cancelled = new JSObject();
            cancelled.put("saved", false);
            cancelled.put("reason", "cancelled");
            call.resolve(cancelled);
            return;
        }

        Uri uri = result.getData().getData();
        if (uri == null) {
            discardTransfer();
            call.reject("the file picker returned no document");
            return;
        }

        // A process that was killed and restarted comes back here with a
        // rehydrated call and no buffer — the state the OLD code died in rather
        // than reported. It is a real state, and the honest thing to say about
        // it is that the archive is gone and the export has to be run again.
        if (staged == null) {
            call.reject("the staged archive was no longer in memory — run the export again");
            return;
        }

        try {
            writeDocument(getContext(), uri, staged);
        } catch (IOException | IllegalArgumentException error) {
            // The engine's own message, never the archive's contents.
            call.reject("the archive could not be written: " + error.getMessage());
            return;
        } finally {
            discardTransfer();
        }

        JSObject saved = new JSObject();
        saved.put("saved", true);
        saved.put("uri", uri.toString());
        call.resolve(saved);
    }

    /** Family bytes do not outlive the export they belong to. */
    private synchronized void discardTransfer() {
        staged = null;
        transferId = null;
        declaredTotalBytes = 0;
    }

    @Override
    protected synchronized void handleOnDestroy() {
        discardTransfer();
    }

    /**
     * Streams the staged archive into the chosen document.
     *
     * <p>{@code writeTo} rather than {@code toByteArray}: the latter copies the
     * whole archive a second time, so the process would hold two multi-megabyte
     * copies at the one moment it is already at its peak. Peak here is one.
     *
     * <p>Extracted from {@link #onDocumentCreated} so the byte path can be
     * exercised on a real device without driving the system file picker's UI —
     * see {@code ExportSinkTest}. The picker is the part an instrumented test
     * cannot honestly automate; the decode and the write are the part that can
     * silently corrupt an archive, so that is the part the test covers.
     *
     * <p>{@code "wt"} truncates: writing a shorter archive over a longer one must
     * not leave the tail of the old file behind, which would produce a zip whose
     * central directory says one thing and whose bytes say another.
     */
    static void writeDocument(android.content.Context context, Uri uri, ByteArrayOutputStream staged)
            throws IOException {
        try (OutputStream out = context.getContentResolver().openOutputStream(uri, "wt")) {
            if (out == null) {
                throw new IOException("the chosen document could not be opened for writing");
            }
            staged.writeTo(out);
            out.flush();
        }
    }
}
