package app.theygrow;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.util.Base64;

import androidx.activity.result.ActivityResult;

import com.getcapacitor.JSObject;
import com.getcapacitor.Logger;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.ActivityCallback;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;

/**
 * The browser-to-native history transfer (DIA-P1, ADR-048).
 *
 * <p>WHAT THIS EXISTS FOR. The family's real history lives in {@code
 * localStorage} under the PRODUCTION origin, in the parent's browser. This app
 * cannot see it: the Capacitor WebView's origin is {@code https://localhost}, a
 * different storage partition, so the L1-P4 importer — complete, idempotent, and
 * incapable of writing to its source ({@code LSC-P4-INV-002}) — has never had
 * anything to import. This plugin is the bridge: the app opens a page on the
 * production origin, that page reads the history and hands it back through a
 * link addressed to this package, and the importer takes it from there.
 *
 * <p><b>STAGED TRANSPORT, AND WHY IT IS A REQUIREMENT RATHER THAN A STYLE.</b>
 * On 2026-08-15 this repository killed a process on the family device with a
 * {@code TransactionTooLargeException} at a 4 630 924-byte parcel, because an
 * archive rode as an option of a plugin call Capacitor persists into saved
 * instance state — twice ({@code XPT-DL-001}). Nothing about that lesson is
 * specific to exporting. So here:
 *
 * <ul>
 *   <li>the Intent is consumed NATIVELY, in {@link MainActivity}, and its
 *       payload is decoded and STAGED in this process before the WebView is told
 *       anything at all;
 *   <li>{@link #pendingTransfer} answers with a reference and small metadata —
 *       a transfer id, a byte count, a digest, a format version — and never the
 *       payload;
 *   <li>{@link #readChunk} hands the staged bytes back in bounded pieces, so no
 *       single bridge call carries more than {@link #TRANSFER_CHUNK_BYTES};
 *   <li>every method refuses an option key it does not declare, and options
 *       above {@link #LAUNCH_OPTIONS_MAX_BYTES}, BEFORE it acts.
 * </ul>
 *
 * <p><b>EVERY REFUSAL PRINTS WHAT IT WAS HANDED, WHERE IT LOOKED, AND WHAT IT
 * FOUND</b> — the URI's scheme and host, the offending key by name, the declared
 * byte count beside the actual one, the ceiling in force. It NEVER prints the
 * payload, and never anything decoded from it: those bytes are a child's name,
 * their birthdate and their history. A verdict that forces a code change to
 * learn its own cause is a defect this repository has already paid for twice
 * (RSN-P3, {@code RSN-DL-004}), and a diagnostic that leaks family data is a
 * different defect that would be worse. Both are avoidable at once, because
 * everything a reader needs is metadata.
 *
 * <p><b>WHAT A REFUSAL COSTS THE PARENT: one line of instruction.</b> Every
 * refusal below is reported to the app as a closed code, and the app switches to
 * the file path — ADR-048 §3, automatic, with no fork presented. Truncation by a
 * browser is the case this matters most for: it arrives as {@code size_mismatch}
 * or {@code checksum_mismatch}, is refused before a byte is staged, and costs a
 * second gesture rather than a partial history written into an append-only
 * journal that can never be corrected.
 *
 * <p>Registered explicitly in {@link MainActivity} for the same reason {@link
 * ExportSinkPlugin} is: {@code capacitor.plugins.json} is generated by {@code
 * cap sync} and gitignored, so it never lists a first-party plugin.
 *
 * <p><b>AND EVERY ONE OF THOSE LINES GOES THROUGH THE GATE NOW (L3-P2,
 * {@code FIU-DL-002}, closing the exposure half of {@code DIA-DL-010} debt
 * 13).</b> They used to be {@code android.util.Log} calls, which is the one
 * sink in this app that {@code loggingBehavior} never reached: {@code
 * DIA-P5-INV-001}'s own Scope had to enumerate this tag as untouched, and run
 * 32074105863 measured seven of its lines standing in a capture whose whole
 * point was that the gate had closed. {@code Logger.warn(tag, message)} keeps
 * the tag string — so this file's diagnostics stay findable under {@code
 * TheyGrowTransfer} the day the gate is deliberately opened — and consults
 * {@code shouldLog()}, which {@code native/capacitor.config.json}'s {@code
 * "loggingBehavior": "none"} answers false in EVERY build.
 *
 * <p><b>What that does NOT do, said plainly because the next reader will want
 * to know:</b> {@link #refuse} still takes a free {@code String}, where {@code
 * emitSignal} structurally cannot. Nothing today hands it family text and
 * nothing but review stops it. The gate removes the sink rather than the
 * shape, so the remaining half of debt 13 — constraining these diagnostics the
 * way signal payloads are constrained — stays open and stays inventoried.
 */
@CapacitorPlugin(name = "TheyGrowTransfer")
public class HistoryTransferPlugin extends Plugin {

    private static final String TAG = "TheyGrowTransfer";

    /**
     * The PWA base URL the handoff page is opened at, and the path on it.
     *
     * <p>The product's PUBLIC address, named as the handoff page's home in
     * ADR-048 §1 — deliberately not the live-infra naming (the Cloud Run service,
     * its region, its generated host), which stays in {@code docs/RUNBOOK.md}.
     *
     * <p>THE EMPTY-VALUE GUARD IN {@link #openHandoff} STAYS. Its subject is now
     * a value that has been emptied — by a refactor, a bad merge, a build that
     * strips a constant — rather than one never supplied. A knob whose unset
     * state is a silent no-op is worse than one that is missing.
     *
     * <p>Mirrors {@code TRANSFER_CONFIG.handoffOrigin} in the mount's {@code
     * transfer/config.js}; {@code app/tests/transfer-seam.spec.js} asserts the
     * two agree and that the refusal branch still exists.
     */
    static final String HANDOFF_ORIGIN = "https://theygrow.app";

    static final String HANDOFF_PATH = "/transfer.html";

    /** The only option keys any method here accepts, per method. */
    private static final List<String> OPEN_HANDOFF_KEYS = Arrays.asList("url");
    private static final List<String> READ_CHUNK_KEYS =
            Arrays.asList("transferId", "offset", "length");
    private static final List<String> DISCARD_KEYS = Arrays.asList("transferId");

    /**
     * The ceiling on any call's serialized options. Mirrors {@code
     * TRANSFER_CONFIG.launchOptionsMaxBytes}; the two languages share no config
     * surface, so the number is written in both places and asserted equal
     * off-device — the arrangement {@code sinkLaunchOptionsMaxBytes} already has
     * with {@link ExportSinkPlugin#LAUNCH_OPTIONS_MAX_BYTES}.
     */
    static final int LAUNCH_OPTIONS_MAX_BYTES = 4096;

    /**
     * The largest chunk {@link #readChunk} will return, raw. Mirrors {@code
     * TRANSFER_CONFIG.transferChunkBytes}.
     */
    static final int TRANSFER_CHUNK_BYTES = 262144;

    /**
     * The ceiling on an encoded payload arriving on a LINK. Mirrors {@code
     * TRANSFER_CONFIG.linkMaxBytes}.
     *
     * <p>The app-side ceiling is the one that decides — the page emits a file
     * instead of building an over-long link — and this is the receiving side
     * saying the same number back, because a guard that trusts the sender to
     * have applied its own guard is not a guard.
     */
    static final int LINK_MAX_BYTES = 16384;

    /**
     * The largest transfer this plugin will stage from a FILE, as a bound on its
     * own heap. Java-only and not a knob in the app's config surface, exactly as
     * {@code MAX_STAGED_BYTES} is in {@link ExportSinkPlugin}: it is a property
     * of the process holding the bytes, and the app could not act on it if it
     * knew it.
     */
    private static final int MAX_STAGED_BYTES = 16 * 1024 * 1024;

    /** The declared query keys on the link. Mirrors TRANSFER_CONFIG.linkParams. */
    private static final String PARAM_PAYLOAD = "payload";
    private static final String PARAM_BYTES = "bytes";
    private static final String PARAM_DIGEST = "sha256";
    private static final String PARAM_VERSION = "v";
    private static final List<String> LINK_PARAM_KEYS =
            Arrays.asList(PARAM_PAYLOAD, PARAM_BYTES, PARAM_DIGEST, PARAM_VERSION);

    /** The envelope format version this build reads. Mirrors ENVELOPE_FORMAT_VERSION. */
    private static final int ENVELOPE_FORMAT_VERSION = 1;

    // Guarded by `this`: the Intent arrives on the main thread and Capacitor
    // dispatches plugin calls on a pool thread, so staging and draining are on
    // different threads by construction.
    private byte[] staged;
    private String transferId;
    private String stagedDigest;
    private String refusal = "none";

    // --- receiving the link --------------------------------------------------

    /**
     * Stages the transfer an incoming link carries, or refuses it by name.
     *
     * <p>Called from {@link MainActivity}, on the main thread, BEFORE the WebView
     * is told anything. Nothing here reaches the bridge and nothing here is
     * reachable from JavaScript: the Intent and its payload never cross into the
     * WebView, which is the whole shape of the transport.
     *
     * <p>The order of the checks is the contract: every one of them happens
     * before a byte is retained, so a refused transfer leaves this plugin holding
     * exactly nothing.
     */
    synchronized void stageFromIntent(Intent intent) {
        if (intent == null || intent.getData() == null) {
            return;
        }
        Uri uri = intent.getData();
        // The only two parts of the URI safe to print. The query holds the
        // family's history; the scheme and the host hold nothing.
        String where = uri.getScheme() + "://" + uri.getHost();
        discard();

        // 1. Foreign option key. Refused first and by NAME, because an
        //    undeclared key is how something rides in that nobody designed for.
        for (String key : uri.getQueryParameterNames()) {
            if (!LINK_PARAM_KEYS.contains(key)) {
                refuse(
                        "foreign_key",
                        "handoff link at "
                                + where
                                + " carries the undeclared query key \""
                                + key
                                + "\"; this build accepts exactly "
                                + LINK_PARAM_KEYS
                                + " — nothing was staged");
                return;
            }
        }

        String payload = uri.getQueryParameter(PARAM_PAYLOAD);
        String declaredBytes = uri.getQueryParameter(PARAM_BYTES);
        String declaredDigest = uri.getQueryParameter(PARAM_DIGEST);
        String declaredVersion = uri.getQueryParameter(PARAM_VERSION);
        if (payload == null || declaredBytes == null || declaredDigest == null
                || declaredVersion == null) {
            refuse(
                    "format_version",
                    "handoff link at "
                            + where
                            + " is missing a required parameter: payload="
                            + (payload == null ? "absent" : "present")
                            + " bytes="
                            + (declaredBytes == null ? "absent" : declaredBytes)
                            + " sha256="
                            + (declaredDigest == null ? "absent" : "present")
                            + " v="
                            + (declaredVersion == null ? "absent" : declaredVersion));
            return;
        }

        // 2. Format version, before anything is decoded. Both directions: a
        //    newer version this build does not understand, and an older one that
        //    was never published.
        int version;
        try {
            version = Integer.parseInt(declaredVersion);
        } catch (NumberFormatException error) {
            refuse(
                    "format_version",
                    "handoff link at " + where + " declares a non-numeric format version \""
                            + declaredVersion + "\"");
            return;
        }
        if (version != ENVELOPE_FORMAT_VERSION) {
            refuse(
                    "format_version",
                    "handoff link at "
                            + where
                            + " is envelope format version "
                            + version
                            + "; this build reads version "
                            + ENVELOPE_FORMAT_VERSION);
            return;
        }

        // 3. The ceiling, before the decode allocates anything. The page is
        //    supposed to have emitted a file instead of a link this long; a link
        //    that arrives anyway is refused rather than trusted.
        if (payload.length() > LINK_MAX_BYTES) {
            refuse(
                    "options_ceiling",
                    "handoff link at "
                            + where
                            + " carries a "
                            + payload.length()
                            + "-character payload; the ceiling in force is "
                            + LINK_MAX_BYTES
                            + " — nothing was staged, and the file path is where a history this"
                            + " size travels");
            return;
        }

        int declared;
        try {
            declared = Integer.parseInt(declaredBytes);
        } catch (NumberFormatException error) {
            refuse(
                    "size_mismatch",
                    "handoff link at " + where + " declares a non-numeric byte count \""
                            + declaredBytes + "\"");
            return;
        }

        byte[] decoded;
        try {
            decoded = Base64.decode(payload, Base64.URL_SAFE | Base64.NO_PADDING | Base64.NO_WRAP);
        } catch (IllegalArgumentException error) {
            // The single most likely real cause, and the reason this reads as a
            // truncation rather than as corruption: a browser that shortened the
            // URI leaves base64 that does not decode.
            refuse(
                    "size_mismatch",
                    "handoff link at "
                            + where
                            + " carries a "
                            + payload.length()
                            + "-character payload that is not decodable base64url — the most"
                            + " likely cause is a URI shortened in transit");
            return;
        }

        // 4. Declared versus actual. THE TRUNCATION CHECK, stated as a
        //    comparison of two numbers so the log says which two.
        if (decoded.length != declared) {
            refuse(
                    "size_mismatch",
                    "handoff link at "
                            + where
                            + " declared "
                            + declared
                            + " bytes and decoded to "
                            + decoded.length
                            + " — nothing was staged");
            return;
        }

        // 5. The digest. Catches a transport that shortened the payload on a
        //    boundary the length check cannot see, and any other alteration.
        String actualDigest = sha256Hex(decoded);
        if (actualDigest == null) {
            refuse("checksum_mismatch", "handoff link at " + where + ": SHA-256 is unavailable on"
                    + " this device, so the transfer cannot be verified");
            return;
        }
        if (!actualDigest.equalsIgnoreCase(declaredDigest)) {
            // NEITHER DIGEST IS PRINTED. A digest of a family history is a
            // stable identifier for that history, and a log line is not a place
            // to put one. The comparison result is what a reader needs.
            refuse(
                    "checksum_mismatch",
                    "handoff link at "
                            + where
                            + " carries "
                            + decoded.length
                            + " bytes whose SHA-256 does not equal the one the link declares"
                            + " — nothing was staged (digests deliberately not logged)");
            return;
        }

        staged = decoded;
        stagedDigest = actualDigest;
        transferId = UUID.randomUUID().toString();
        refusal = "none";
        Logger.info(TAG, "staged a handoff of " + decoded.length + " bytes from " + where);
    }

    // --- the bridge surface --------------------------------------------------

    /**
     * Opens the handoff page in the parent's browser.
     *
     * <p>The URL is built HERE, from this class's own constants, and the one
     * option the call may carry is checked against it. An app-side edit therefore
     * cannot turn the transfer button into an arbitrary browser-open, and the two
     * declarations are asserted equal off-device.
     */
    @PluginMethod
    public void openHandoff(PluginCall call) {
        if (refuseOptions(call, OPEN_HANDOFF_KEYS, "openHandoff")) {
            return;
        }
        if (HANDOFF_ORIGIN.isEmpty()) {
            String message =
                    "openHandoff refuses: the PWA origin is not configured in this build."
                            + " HANDOFF_ORIGIN in HistoryTransferPlugin.java and"
                            + " TRANSFER_CONFIG.handoffOrigin in the mount are both empty, which"
                            + " is their shipped default — the serving URL is not recorded in the"
                            + " repository. See docs/RUNBOOK.md. Nothing was started.";
            Logger.warn(TAG, message);
            call.reject(message, "handoff_unconfigured");
            return;
        }

        String expected = HANDOFF_ORIGIN + HANDOFF_PATH;
        String asked = call.getString("url");
        if (asked != null && !expected.equals(asked)) {
            // The value IS printed: it is a URL this build declines to open, not
            // family data, and a reader cannot act on "some other URL".
            String message =
                    "openHandoff refuses the url \""
                            + asked
                            + "\": this plugin opens exactly \""
                            + expected
                            + "\" and nothing else. Nothing was started.";
            Logger.warn(TAG, message);
            call.reject(message, "handoff_foreign_url");
            return;
        }

        Intent browse = new Intent(Intent.ACTION_VIEW, Uri.parse(expected));
        browse.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        try {
            getContext().startActivity(browse);
        } catch (RuntimeException error) {
            String message =
                    "openHandoff could not start a browser for \""
                            + expected
                            + "\": "
                            + error.getClass().getSimpleName()
                            + ". Nothing was started.";
            Logger.warn(TAG, message);
            call.reject(message, "no_browser");
            return;
        }
        call.resolve(new JSObject().put("opened", true));
    }

    /**
     * What is staged, as a reference and small metadata — never the payload.
     *
     * <p>This is the call that makes the transport staged rather than parcelled:
     * whatever the size of the history, what crosses the bridge here is an id, a
     * count, a digest and a version.
     */
    @PluginMethod
    public synchronized void pendingTransfer(PluginCall call) {
        JSObject result = new JSObject();
        if (staged == null) {
            result.put("present", false);
            result.put("refusal", refusal);
            call.resolve(result);
            return;
        }
        result.put("present", true);
        result.put("refusal", "none");
        result.put("transferId", transferId);
        result.put("totalBytes", staged.length);
        result.put("sha256", stagedDigest);
        result.put("formatVersion", ENVELOPE_FORMAT_VERSION);
        call.resolve(result);
    }

    /** Hands back one bounded piece of the staged transfer. */
    @PluginMethod
    public synchronized void readChunk(PluginCall call) {
        if (refuseOptions(call, READ_CHUNK_KEYS, "readChunk")) {
            return;
        }

        String id = call.getString("transferId");
        if (staged == null || transferId == null || !transferId.equals(id)) {
            String message =
                    "readChunk names no open transfer: this plugin holds "
                            + (staged == null ? "nothing" : "a different transfer")
                            + " and the call asked for "
                            + (id == null ? "no id at all" : "an id it does not match");
            Logger.warn(TAG, message);
            call.reject(message, "no_transfer");
            return;
        }

        Integer offset = call.getInt("offset");
        Integer length = call.getInt("length");
        if (offset == null || length == null || offset < 0 || length <= 0) {
            String message =
                    "readChunk needs a non-negative offset and a positive length; it was handed"
                            + " offset="
                            + offset
                            + " length="
                            + length
                            + " against "
                            + staged.length
                            + " staged bytes";
            Logger.warn(TAG, message);
            call.reject(message, "bad_range");
            return;
        }
        if (length > TRANSFER_CHUNK_BYTES) {
            String message =
                    "readChunk refuses a length of "
                            + length
                            + ": the ceiling in force is "
                            + TRANSFER_CHUNK_BYTES
                            + " bytes per call, so that no single bridge call approaches the"
                            + " binder limit. Nothing was returned.";
            Logger.warn(TAG, message);
            call.reject(message, "options_ceiling");
            return;
        }
        if (offset >= staged.length) {
            String message =
                    "readChunk was handed offset "
                            + offset
                            + " against "
                            + staged.length
                            + " staged bytes — the transfer has already been read to its end";
            Logger.warn(TAG, message);
            call.reject(message, "bad_range");
            return;
        }

        int end = Math.min(offset + length, staged.length);
        byte[] slice = Arrays.copyOfRange(staged, offset, end);
        JSObject result = new JSObject();
        result.put("base64", Base64.encodeToString(slice, Base64.NO_WRAP));
        result.put("offset", offset);
        result.put("bytes", slice.length);
        result.put("done", end >= staged.length);
        call.resolve(result);
    }

    /** Drops the staged transfer. Family bytes do not outlive the transfer. */
    @PluginMethod
    public synchronized void discardTransfer(PluginCall call) {
        if (refuseOptions(call, DISCARD_KEYS, "discardTransfer")) {
            return;
        }
        discard();
        refusal = "none";
        call.resolve(new JSObject().put("discarded", true));
    }

    // --- fallback A: the parent picks the file the page emitted --------------

    /**
     * Opens the system document picker and stages what the parent chooses.
     *
     * <p>{@code ACTION_OPEN_DOCUMENT} needs NO storage permission: the system
     * hands back a URI for the single document the parent picked in that moment,
     * and this plugin can read that document and nothing else. It cannot list a
     * directory, cannot choose a path of its own and cannot write anywhere — the
     * mirror of the argument {@code LSC-P3-INV-002} makes for the export sink's
     * {@code ACTION_CREATE_DOCUMENT}.
     */
    @PluginMethod
    public void pickTransfer(PluginCall call) {
        if (refuseOptions(call, Arrays.asList(), "pickTransfer")) {
            return;
        }
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        // Deliberately broad: a browser may hand a .json download any of several
        // MIME types, and a parent who cannot see their own file in the picker
        // has no way to proceed. What is read is validated by content — format
        // id, version, digest — not by the type the filesystem guessed.
        intent.setType("*/*");
        bridge.saveCall(call);
        startActivityForResult(call, intent, "onTransferPicked");
    }

    @ActivityCallback
    private synchronized void onTransferPicked(PluginCall call, ActivityResult result) {
        if (call == null) {
            return;
        }
        if (result.getResultCode() != Activity.RESULT_OK || result.getData() == null
                || result.getData().getData() == null) {
            // A closed picker is a decision, not a failure — the same posture
            // the export sink takes.
            JSObject cancelled = new JSObject();
            cancelled.put("present", false);
            cancelled.put("refusal", "cancelled");
            call.resolve(cancelled);
            return;
        }

        Uri uri = result.getData().getData();
        discard();
        byte[] bytes;
        try {
            bytes = readDocument(uri);
        } catch (IOException | SecurityException error) {
            // The engine's class only. A content URI names a place in the
            // parent's filesystem and its message can carry a path.
            String message =
                    "the chosen document could not be read ("
                            + error.getClass().getSimpleName()
                            + "); nothing was staged";
            Logger.warn(TAG, message);
            call.reject(message, "unreadable");
            return;
        }
        if (bytes.length == 0 || bytes.length > MAX_STAGED_BYTES) {
            String message =
                    "the chosen document is "
                            + bytes.length
                            + " bytes; this build stages between 1 and "
                            + MAX_STAGED_BYTES
                            + " — nothing was staged";
            Logger.warn(TAG, message);
            call.reject(message, "options_ceiling");
            return;
        }

        staged = bytes;
        stagedDigest = sha256Hex(bytes);
        transferId = UUID.randomUUID().toString();
        refusal = "none";
        Logger.info(TAG, "staged a picked transfer of " + bytes.length + " bytes");

        JSObject out = new JSObject();
        out.put("present", true);
        out.put("refusal", "none");
        out.put("transferId", transferId);
        out.put("totalBytes", bytes.length);
        out.put("sha256", stagedDigest);
        // The picked file is not the link, so its envelope version is whatever
        // the file says. The APP parses and refuses it — see transfer/format.js —
        // and this is reported so the two sides agree about what was staged.
        out.put("formatVersion", ENVELOPE_FORMAT_VERSION);
        call.resolve(out);
    }

    // --- shared guards -------------------------------------------------------

    /**
     * Refuses an undeclared option key or oversized options, before anything acts.
     *
     * <p>Returns true when it refused. Same guard class as {@link
     * ExportSinkPlugin#createDocument} and for the same measured reason: an
     * option key nobody declared is how a payload gets onto a call, and options
     * are what Capacitor persists.
     */
    private boolean refuseOptions(PluginCall call, List<String> declared, String method) {
        JSObject data = call.getData();
        Iterator<String> keys = data.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            if (!declared.contains(key)) {
                String message =
                        method
                                + " refuses the option \""
                                + key
                                + "\": this call declares exactly "
                                + declared
                                + " and carries a reference to a staged transfer, never a"
                                + " payload. Nothing was done.";
                Logger.warn(TAG, message);
                call.reject(message, "foreign_key");
                return true;
            }
        }
        int optionsBytes = data.toString().length();
        if (optionsBytes > LAUNCH_OPTIONS_MAX_BYTES) {
            String message =
                    method
                            + " refuses "
                            + optionsBytes
                            + " bytes of options: the ceiling in force is "
                            + LAUNCH_OPTIONS_MAX_BYTES
                            + " bytes, because options are what Capacitor persists into saved"
                            + " instance state. Nothing was done.";
            Logger.warn(TAG, message);
            call.reject(message, "options_ceiling");
            return true;
        }
        return false;
    }

    /**
     * Records a refusal and logs its bounded evidence.
     *
     * <p>The code is what {@link #pendingTransfer} reports to the app, and it is
     * a member of the closed {@code refusal} list in the mount's {@code
     * core/signals.js} — so a refusal can be counted in a signal without any
     * free string existing anywhere on the path.
     */
    private void refuse(String code, String evidence) {
        discard();
        refusal = code;
        Logger.warn(TAG, code + ": " + evidence);
    }

    private void discard() {
        staged = null;
        transferId = null;
        stagedDigest = null;
    }

    @Override
    protected synchronized void handleOnDestroy() {
        discard();
        refusal = "none";
    }

    private byte[] readDocument(Uri uri) throws IOException {
        try (InputStream in = getContext().getContentResolver().openInputStream(uri)) {
            if (in == null) {
                throw new IOException("the chosen document could not be opened");
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[64 * 1024];
            int read;
            while ((read = in.read(buffer)) != -1) {
                if (out.size() + read > MAX_STAGED_BYTES) {
                    // Stop at the bound rather than after it: a runaway file
                    // must not be fully materialised just to be rejected.
                    out.write(buffer, 0, read);
                    return out.toByteArray();
                }
                out.write(buffer, 0, read);
            }
            return out.toByteArray();
        }
    }

    /** Lower-case hex SHA-256, or null when the device has no such digest. */
    static String sha256Hex(byte[] bytes) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(bytes);
            StringBuilder out = new StringBuilder(digest.length * 2);
            for (byte b : digest) {
                out.append(Character.forDigit((b >> 4) & 0xf, 16));
                out.append(Character.forDigit(b & 0xf, 16));
            }
            return out.toString();
        } catch (NoSuchAlgorithmException error) {
            return null;
        }
    }

    /** Test seam: stage bytes exactly as a picked document would. */
    static byte[] utf8(String text) {
        return text.getBytes(StandardCharsets.UTF_8);
    }
}
