package app.theygrow;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    /**
     * Registers the first-party plugins (L1-P3 export sink, NAV-P2 build info).
     *
     * <p>{@code capacitor.plugins.json} is generated by {@code cap sync} and is
     * gitignored, so it lists only plugins that arrive through npm and never a
     * first-party one. Registration therefore happens here, before
     * {@code super.onCreate} starts the bridge — a plugin registered afterwards
     * is not visible to the WebView that has already loaded.
     *
     * <p>NAV-P2 ADDS THE SECOND ONE THIS APP CURRENTLY HAS. {@link
     * BuildInfoPlugin} reports the installed {@code versionCode} and the package
     * that installed it — the two facts the update check needs and the only two
     * it takes from the device. It is registered here for the same reason and by
     * the same rule as the export sink, and before {@code super.onCreate} for the
     * same reason: a plugin registered after the bridge has started is invisible
     * to the WebView that has already loaded.
     *
     * <p>THERE WAS ANOTHER ONE, AND PPR-P2 RETIRED IT. {@code
     * HistoryTransferPlugin} received the browser-to-native history handoff and
     * consumed its Intent here, before the WebView could see it. It is gone with
     * the whole mechanism (owner decision 2026-08-22): its last product caller
     * went with the offer surface at L3-P2, and the one browser history it
     * existed for has been carried across and confirmed on a device. What the
     * app registers is what the app offers.
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(ExportSinkPlugin.class);
        registerPlugin(BuildInfoPlugin.class);
        super.onCreate(savedInstanceState);
    }

    /**
     * Replaces the bridge's console handler with one that writes signal lines
     * and nothing else (DIA-P5).
     *
     * <p>WHY HERE AND NOT IN {@code onCreate}. Capacitor builds its own
     * {@code BridgeWebChromeClient} in {@code Bridge.loadWebView()}
     * ({@code Bridge.java:280}), which the bridge's constructor calls on its way
     * out, so there is nothing to replace until
     * {@code super.load()} has returned — and the bridge exposes no hook for
     * supplying one, so {@code setWebChromeClient} after the fact is the only
     * door. {@code load()} is called from {@code BridgeActivity.onCreate}, which
     * is the window this has to happen in.
     *
     * <p>AND THE WINDOW IS NARROW IN A WAY THAT BITES. The replacement's
     * super-constructor calls {@code bridge.registerForActivityResult} twice,
     * and {@code ActivityResultRegistry.register} throws
     * {@code IllegalStateException} once the activity is at or past
     * {@code STARTED} — "LifecycleOwners must call register before they are
     * STARTED". Moved to {@code onStart}, {@code onResume} or
     * {@code onPostCreate}, this line is a crash on the family's first tap
     * rather than a subtle regression. Capacitor registers those same two
     * launchers from inside this very call stack today, which is what says the
     * moment is legal.
     *
     * <p>NOTHING IS MISSED IN BETWEEN. {@code loadWebView()} ends by asking the
     * WebView to load the app URL, which is asynchronous; the UI thread is still
     * inside {@code onCreate} here, so no page script has run and no console
     * message can have been delivered to the client being replaced. The
     * boot-time {@code store.open} signal is the first line either way, and
     * {@code DeviceLogTest} asserts it arrives.
     */
    @Override
    protected void load() {
        super.load();
        getBridge().getWebView().setWebChromeClient(new SignalConsoleClient(getBridge()));
    }
}
