package app.theygrow;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    /**
     * Registers the first-party export sink (L1-P3).
     *
     * <p>{@code capacitor.plugins.json} is generated by {@code cap sync} and is
     * gitignored, so it lists only plugins that arrive through npm and never a
     * first-party one. Registration therefore happens here, before
     * {@code super.onCreate} starts the bridge — a plugin registered afterwards
     * is not visible to the WebView that has already loaded.
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(ExportSinkPlugin.class);
        super.onCreate(savedInstanceState);
    }
}
