package app.theygrow;

import android.content.Intent;
import android.os.Bundle;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    /**
     * Registers the first-party plugins (L1-P3 export sink; DIA-P1 transfer).
     *
     * <p>{@code capacitor.plugins.json} is generated by {@code cap sync} and is
     * gitignored, so it lists only plugins that arrive through npm and never a
     * first-party one. Registration therefore happens here, before
     * {@code super.onCreate} starts the bridge — a plugin registered afterwards
     * is not visible to the WebView that has already loaded.
     *
     * <p>THE INTENT IS CONSUMED BEFORE THE WEBVIEW SEES IT, and that ordering is
     * the transport rather than a detail. A handoff link carries the family's
     * history in its query; if the WebView were handed the Intent, the payload
     * would cross the bridge as a parcel — which is the shape that killed this
     * process at 4 630 924 bytes on 2026-08-15 ({@code XPT-DL-001}). Instead the
     * plugin decodes and stages it natively here, and the WebView later asks
     * {@code pendingTransfer()} and receives an id, a byte count and a digest.
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(ExportSinkPlugin.class);
        registerPlugin(HistoryTransferPlugin.class);
        super.onCreate(savedInstanceState);
        stageHandoff(getIntent());
    }

    /**
     * The launch case that actually happens.
     *
     * <p>The activity is {@code launchMode="singleTask"}, so a parent who leaves
     * the app open, walks through the handoff page and comes back does NOT get a
     * fresh {@code onCreate} — the link arrives here. Handling only
     * {@code onCreate} would work exactly once, on a cold start, and would look
     * like an intermittent failure rather than a missing branch.
     */
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
        stageHandoff(intent);
    }

    /**
     * Hands the Intent to the transfer plugin, if it is one.
     *
     * <p>Silent when the Intent carries no data rather than fatal: a launcher tap
     * carries none, and an exception on the app's own start path would be a worse
     * failure than a transfer that has to be started again.
     */
    private void stageHandoff(Intent intent) {
        if (intent == null || intent.getData() == null) {
            return;
        }
        HistoryTransferPlugin plugin =
                (HistoryTransferPlugin)
                        getBridge().getPlugin("TheyGrowTransfer").getInstance();
        plugin.stageFromIntent(intent);
    }
}
